INSERT INTO PUBLISHER(PUBLISHER_CODE, PUBLISHER_NAME, CITY) VALUES('001', 'Vibulkij', 'Bangkok')
INSERT INTO PUBLISHER(PUBLISHER_CODE, PUBLISHER_NAME, CITY) VALUES('002', 'Nation', 'Bangkok')
INSERT INTO PUBLISHER(PUBLISHER_CODE, PUBLISHER_NAME, CITY) VALUES('003', 'Siam Inter Comics', 'Bangkok')

INSERT INTO AUTHOR(AUTHOR_CODE, FIRST_NAME, LAST_NAME) VALUES('001', 'A', 'B');
INSERT INTO AUTHOR(AUTHOR_CODE, FIRST_NAME, LAST_NAME) VALUES('002', 'C', 'D');
INSERT INTO AUTHOR(AUTHOR_CODE, FIRST_NAME, LAST_NAME) VALUES('003', 'E', 'F');

INSERT INTO BOOK(TITLE, PRICE, PUBLISHER_CODE, AUTHOR_CODE) VALUES ('Naruto', '55', '002', '001');
INSERT INTO BOOK(TITLE, PRICE, PUBLISHER_CODE, AUTHOR_CODE) VALUES ('Jojo', '65', '002', '001');
INSERT INTO BOOK(TITLE, PRICE, PUBLISHER_CODE, AUTHOR_CODE) VALUES ('xxxHolic', '55', '001', '002');
INSERT INTO BOOK(TITLE, PRICE, PUBLISHER_CODE, AUTHOR_CODE) VALUES ('Sayonara Zettsubo', '55', '001', '002');
INSERT INTO BOOK(TITLE, PRICE, PUBLISHER_CODE, AUTHOR_CODE) VALUES ('Sidooh', '55', '003', '003');
INSERT INTO BOOK(TITLE, PRICE, PUBLISHER_CODE, AUTHOR_CODE) VALUES ('Gunslinger Girl', '55', '003', '003');